### ISSUE TITLE
השלב הראשון בעמוד הזמנת אוכל

### ISSUE THREAD

**Issue by MayaSasson** [RoeiRom/NewSpectrum-Client#2]
![image](https://user-images.githubusercontent.com/62544146/78054561-f3221680-738a-11ea-9e42-6879cd32d117.png)

בעמוד הזמנת אוכל נוסף stepper אותו ניתן לקחת מvuetify
https://vuetifyjs.com/en/components/steppers/#steppers
![image](https://user-images.githubusercontent.com/62544146/78054721-2664a580-738b-11ea-836e-133f8df94cad.png)
בעת כניסה לעמוד השלב הראשון בסטפר יהיה לחוץ ובו ניתן לראות שדה בו אפשר להקליד שם אופציה אפשרית של מקום בו ניתן לאכול.
*בעת לחיצה על כפתור: 
![image](https://user-images.githubusercontent.com/62544146/78054965-85c2b580-738b-11ea-8d46-03d87efb7316.png) שם המסעדה יתווסף לרשימת הגלילה.
*כאשר המשתמש לוחץ על השדה בחירה: 
![image](https://user-images.githubusercontent.com/62544146/78055183-d0dcc880-738b-11ea-946c-d717e92a1e02.png) תפתח רשימת הגלילה ובה האופציות שמשתמשים נוספים כבר הזינו. 
*במידה והמשתמש שנכנס לדף זה הוא המשתמש הראשון אשר מזין אופצית בחירה לא תפתח רשימת גלילה (משום שהיא עדיין לא קיימת)
*בלחיצה על כפתור "המשך" נעבור לשלב השני.

**שדה הבחירה נלקח מvuetify גם כן 
![image](https://user-images.githubusercontent.com/62544146/78055946-ff0ed800-738c-11ea-8a56-7eff653bd731.png)
https://vuetifyjs.com/en/components/text-fields/

הערות:
- יש לקחת את המסעדות שאפשר להזמין מהם מהDB
- כאשר מוסיפים מסעדה חדשה, יש להוסיף אותה ל-DB

**Comment by MayaSasson** [comment]
תמונות המופיעות בעמוד:

![image](https://user-images.githubusercontent.com/62544146/78055989-0f26b780-738d-11ea-91fe-3b2f1b432b92.png)

![image](https://user-images.githubusercontent.com/62544146/78056012-15b52f00-738d-11ea-8870-ace760bea9f6.png)

![image](https://user-images.githubusercontent.com/62544146/78056026-1b127980-738d-11ea-80f2-22ab2f4e503b.png)

![image](https://user-images.githubusercontent.com/62544146/78056037-1fd72d80-738d-11ea-9eeb-aa9f31f95a89.png)

**Comment by MayaSasson** [comment]
האייקון: ![image](https://user-images.githubusercontent.com/62544146/79067641-892e3900-7cc9-11ea-8ef7-47b547384912.png)
לינק: https://material.io/resources/icons/?search=send&icon=send&style=baseline

**Comment by ronisch2** [comment]
האייקון החדש:
https://material.io/resources/icons/?search=arrow&icon=navigate_before&style=baseline
![image](https://user-images.githubusercontent.com/62544146/79128530-5610a600-7dac-11ea-8922-289267dfda4f.png)
בhover על האייקון תופיע מסגרת מעוגלת בצבע אפרפר:
![image](https://user-images.githubusercontent.com/62544146/79128616-80fafa00-7dac-11ea-8099-6ab847d88443.png)
