### ISSUE TITLE
Hover על שמות המזמינים בשלב השני בהזמנת אוכל

### ISSUE THREAD

**Issue by ronisch2** [RoeiRom/NewSpectrum-Client#24]
בhover על שמות המזמינים (השמות אשר בcheck box שלהם מופיע סימון V) יפתח חלון אשר בו יהיה כתוב שם המסעדה אשר מעוניין המשתמש להזמין ממנה
![image](https://user-images.githubusercontent.com/62544146/79066986-9f85c600-7cc4-11ea-82cc-29568eae88bc.png)

**Comment by ronisch2** [comment]
https://vuetifyjs.com/en/components/tooltips/

**Comment by MayaSasson** [comment]
Merged to #16
