### ISSUE TITLE
כפתור שלח בשלב הראשון בעמוד הזמנת אוכל

### ISSUE THREAD

**Issue by ronisch2** [RoeiRom/NewSpectrum-Client#26]
![image](https://user-images.githubusercontent.com/62544146/79067641-892e3900-7cc9-11ea-8ef7-47b547384912.png)

**Comment by ronisch2** [comment]
https://material.io/resources/icons/?search=send&icon=send&style=baseline

**Comment by MayaSasson** [comment]
added as a comment to #2

**Comment by ronisch2** [comment]
![image](https://user-images.githubusercontent.com/62544146/79112568-82fe9200-7d87-11ea-9961-5cc2c4e6817e.png)
תעדכן אם זה בסדר
