### ISSUE TITLE
התחברות למערכת

### ISSUE THREAD

**Issue by ronisch2** [RoeiRom/NewSpectrum-Client#31]
![image](https://user-images.githubusercontent.com/62544146/79130950-73e00a00-7db0-11ea-99d2-2afc8371bd4c.png)
דף התחברות למערכת יופיע כאשר נכנסים למערכת, לאחר לחיצה על כפתור "התחבר" המערכת תציג אוטומטית את הדף הראשון של הלוח שנה (כאשר הכפתור של לוח השנה בtoolbar לחוץ).
-בלחיצה על הcheckbox "זכור אותי" (checkbox זה הופיע גם כן בעמוד הזמנת אוכל) המערכת תזכור את המשתמש אוטומטית לפי שמו ותכניס אותו למערכת מבלי להזין שנית את שם המשתמש והססמא 
כלומר, המערכת תציג את שם המשתמש והססמא וכל מה שנותר למשתמש לעשות זה ללחוץ על כפתור "התחבר" על מנת לעבור לעמוד הבא

**Comment by ronisch2** [comment]
![image](https://user-images.githubusercontent.com/62544146/79131376-316afd00-7db1-11ea-827e-cd17b2223287.png) -מvuetify
https://material.io/resources/icons/?search=person&icon=perm_identity&style=baseline
![image](https://user-images.githubusercontent.com/62544146/79131436-447dcd00-7db1-11ea-8dc2-7dfa907bbeee.png)- מגוגל

**Comment by ronisch2** [comment]
כרטיס ההתחברות יוצג כאשר יש back drop לרקע

**Comment by MayaSasson** [comment]
תהיה האופציה לראות/לא לראות את הססמא בעת הזנת הססמא, כך שיופיע אייקון של עין בצד השדה:
![image](https://user-images.githubusercontent.com/62544146/79447767-04089400-7fe9-11ea-9735-6c3baeddcdb8.png)
הdefault יהיה שלא יהיה ניתן לראות את הססמא.
בלחיצה על אייקון העין יהיה ניתן לראות את הססמא, וסימון האלכסון על האייקון יתבטל.

שימוש בvuetify:
https://vuetifyjs.com/en/components/text-fields/

![image](https://user-images.githubusercontent.com/62544146/79447916-4205b800-7fe9-11ea-8041-9113dd7b7bfa.png)

![image](https://user-images.githubusercontent.com/62544146/79447956-4f22a700-7fe9-11ea-9736-8cdf3ddb66dd.png)

**Comment by MayaSasson** [comment]
בעת התחברות למערכת כאשר מזינים ססמא/ שם משתמש לא נכונים, המשתמש מגיע ידנית לפתור את תקלה ביחד עם מנהל המערכת.
תופיע הודעת שגיאה:
![image](https://user-images.githubusercontent.com/62544146/79447419-7fb61100-7fe8-11ea-8c30-c8b1b50c80e2.png)
וכאשר הdb לא עובד, תופיע הודעת שגיאה (לאחר ניסיון התחברות - לחיצה על כפתור התחברות):
![image](https://user-images.githubusercontent.com/62544146/79447544-b12edc80-7fe8-11ea-88c3-142868ab7496.png)
