### ISSUE TITLE
הודעות שגיאה בעמוד התחברות

### ISSUE THREAD

**Issue by ronisch2** [RoeiRom/NewSpectrum-Client#33]
בעת התחברות למערכת כאשר מזינים ססמא/ שם משתמש לא נכונים, המשתמש מגיע ידנית לפתור את תקלה ביחד עם מנהל המערכת.
תופיע הודעת שגיאה:
![image](https://user-images.githubusercontent.com/62544146/79447419-7fb61100-7fe8-11ea-8c30-c8b1b50c80e2.png)
וכאשר הdb לא עובד, תופיע הודעת שגיאה (לאחר ניסיון התחברות - לחיצה על כפתור התחברות):
![image](https://user-images.githubusercontent.com/62544146/79447544-b12edc80-7fe8-11ea-88c3-142868ab7496.png)

**Comment by MayaSasson** [comment]
Added as a comment to #31
