### ISSUE TITLE
ניהול הסיסמא במסך ההתחברות

### ISSUE THREAD

**Issue by ronisch2** [RoeiRom/NewSpectrum-Client#34]
תהיה האופציה לראות/לא לראות את הססמא בעת הזנת הססמא, כך שיופיע אייקון של עין בצד השדה:
![image](https://user-images.githubusercontent.com/62544146/79447767-04089400-7fe9-11ea-9735-6c3baeddcdb8.png)
הdefault יהיה שלא יהיה ניתן לראות את הססמא.
בלחיצה על אייקון העין יהיה ניתן לראות את הססמא, וסימון האלכסון על האייקון יתבטל.

שימוש בvuetify:
https://vuetifyjs.com/en/components/text-fields/

![image](https://user-images.githubusercontent.com/62544146/79447916-4205b800-7fe9-11ea-8041-9113dd7b7bfa.png)

![image](https://user-images.githubusercontent.com/62544146/79447956-4f22a700-7fe9-11ea-9736-8cdf3ddb66dd.png)

**Comment by MayaSasson** [comment]
Added as a comment to #31
